# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ZegoUIKitPrebuiltLiveStreamingOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZegoUIKitPrebuiltLiveStreamingOC
  pod 'ZegoUIKitPrebuiltLiveStreaming'

  target 'ZegoUIKitPrebuiltLiveStreamingOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZegoUIKitPrebuiltLiveStreamingOCUITests' do
    # Pods for testing
  end

end
